/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package view.logbook;

import DAO.AnaliseDAO;
import DAO.LoteDAO;
import DAO.MaterialDAO;
import model.Analise;
import model.Lote;
import model.Material;
import util.ComboBox;
import util.DataHora;
import java.awt.HeadlessException;
import java.util.Calendar;
import java.util.Date;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rafael.lopes
 */
public class FrmLoteCromatografo extends javax.swing.JDialog {

    private boolean novoEntradaProduto = false;
    private int idProduto;
    private TreeMap<Integer, String> categoryMap = new TreeMap<>();

    /**
     * Creates new form FrmLoteCromatografo
     *
     * @param parent
     * @param modal
     */
    public FrmLoteCromatografo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Lotes");
        txtEntradaProduto.setMaxSelectableDate(new Date());
        pnlProdutos.setEnabledAt(1, false);
        abrirDados();
    }

    public FrmLoteCromatografo(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Lotes");
        txtEntradaProduto.setMaxSelectableDate(new Date());
        pnlProdutos.setEnabledAt(1, false);
        idProduto = id;
        carregarDadosCadastroProduto(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProdutos = new javax.swing.JTabbedPane();
        pnlDados = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtMaterial = new javax.swing.JTextField();
        txtIdProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCodMaterial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbFinalidadeProduto = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtObsProduto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtLoteProduto = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtEntradaProduto = new com.toedter.calendar.JDateChooser();
        btnSalvarCadastroProduto1 = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        pnlPesquisar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSelecionarProduto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisarCadastroProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditarCadastroProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDados.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabel5.setText("Produto:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_config_produto.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtMaterial.setEditable(false);
        txtMaterial.setBackground(new java.awt.Color(204, 204, 204));
        txtMaterial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtIdProduto.setEditable(false);
        txtIdProduto.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setText("Código:");

        jLabel3.setText("Tipo:");

        txtTipo.setEditable(false);
        txtTipo.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setText("Material:");

        txtCodMaterial.setEditable(false);
        txtCodMaterial.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setText("Finalidade:");

        jLabel2.setText("Obs:");

        jLabel1.setText("Lote:");

        jLabel24.setText("Entrada:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObsProduto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEntradaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTipo)
                                .addComponent(txtCodMaterial)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIdProduto))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbFinalidadeProduto, 0, 180, Short.MAX_VALUE)
                                .addComponent(txtLoteProduto)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbFinalidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLoteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEntradaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtObsProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvarCadastroProduto1.setText("Salvar");
        btnSalvarCadastroProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroProduto1ActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarCadastroProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvarCadastroProduto1))
                .addContainerGap())
        );

        pnlProdutos.addTab("Produto", pnlDados);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSelecionarProduto.setText("Selecionar");
        btnSelecionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarProdutoActionPerformed(evt);
            }
        });

        jLabel4.setText("Pesquisar:");

        txtPesquisarCadastroProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarCadastroProdutoKeyReleased(evt);
            }
        });

        tblEditarCadastroProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Material", "Produto", "Tipo", "Método", "metodo_id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEditarCadastroProduto.setSurrendersFocusOnKeystroke(true);
        tblEditarCadastroProduto.getTableHeader().setReorderingAllowed(false);
        tblEditarCadastroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEditarCadastroProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEditarCadastroProduto);
        if (tblEditarCadastroProduto.getColumnModel().getColumnCount() > 0) {
            tblEditarCadastroProduto.getColumnModel().getColumn(0).setMinWidth(50);
            tblEditarCadastroProduto.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblEditarCadastroProduto.getColumnModel().getColumn(0).setMaxWidth(50);
            tblEditarCadastroProduto.getColumnModel().getColumn(1).setMinWidth(100);
            tblEditarCadastroProduto.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblEditarCadastroProduto.getColumnModel().getColumn(1).setMaxWidth(100);
            tblEditarCadastroProduto.getColumnModel().getColumn(3).setMinWidth(100);
            tblEditarCadastroProduto.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblEditarCadastroProduto.getColumnModel().getColumn(3).setMaxWidth(100);
            tblEditarCadastroProduto.getColumnModel().getColumn(4).setMinWidth(120);
            tblEditarCadastroProduto.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblEditarCadastroProduto.getColumnModel().getColumn(4).setMaxWidth(120);
            tblEditarCadastroProduto.getColumnModel().getColumn(5).setMinWidth(0);
            tblEditarCadastroProduto.getColumnModel().getColumn(5).setPreferredWidth(0);
            tblEditarCadastroProduto.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        javax.swing.GroupLayout pnlPesquisarLayout = new javax.swing.GroupLayout(pnlPesquisar);
        pnlPesquisar.setLayout(pnlPesquisarLayout);
        pnlPesquisarLayout.setHorizontalGroup(
            pnlPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesquisarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSelecionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                    .addGroup(pnlPesquisarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisarCadastroProduto)))
                .addContainerGap())
        );
        pnlPesquisarLayout.setVerticalGroup(
            pnlPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPesquisarCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSelecionarProduto))
                .addContainerGap())
        );

        pnlProdutos.addTab("Pesquisar", pnlPesquisar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProdutos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlProdutos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEditarCadastroProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEditarCadastroProdutoMouseClicked
        if (evt.getClickCount() == 2) {
            if (!tblEditarCadastroProduto.isEnabled()) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar o produto?", "Aviso", JOptionPane.YES_NO_OPTION);
                if (dialogResult == 0) {
                    tblEditarCadastroProduto.setEnabled(true);
                    txtPesquisarCadastroProduto.setEnabled(true);
                }
            } else {
                txtIdProduto.setText(tblEditarCadastroProduto.getValueAt(tblEditarCadastroProduto.getSelectedRow(), 0).toString());
                txtCodMaterial.setText(tblEditarCadastroProduto.getValueAt(tblEditarCadastroProduto.getSelectedRow(), 1).toString());
                txtMaterial.setText(tblEditarCadastroProduto.getValueAt(tblEditarCadastroProduto.getSelectedRow(), 2).toString());
                txtTipo.setText(tblEditarCadastroProduto.getValueAt(tblEditarCadastroProduto.getSelectedRow(), 3).toString());
                pnlProdutos.setEnabledAt(0, true);
                pnlProdutos.setEnabledAt(1, false);
                pnlProdutos.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_tblEditarCadastroProdutoMouseClicked

    private void txtPesquisarCadastroProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarCadastroProdutoKeyReleased
        TableRowSorter sorter = null;
        DefaultTableModel model = (DefaultTableModel) tblEditarCadastroProduto.getModel();
        sorter = new TableRowSorter<>(model);
        tblEditarCadastroProduto.setRowSorter(sorter);
        String text = txtPesquisarCadastroProduto.getText().trim();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }
    }//GEN-LAST:event_txtPesquisarCadastroProdutoKeyReleased

    private void btnSelecionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarProdutoActionPerformed
        if (tblEditarCadastroProduto.getSelectedRow() != -1) {
            if (!tblEditarCadastroProduto.isEnabled()) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja realmente alterar o produto?", "Aviso", JOptionPane.YES_NO_OPTION);
                if (dialogResult == 0) {
                    tblEditarCadastroProduto.setEnabled(true);
                    txtPesquisarCadastroProduto.setEnabled(true);
                }
            } else {
                txtIdProduto.setText(tblEditarCadastroProduto.getValueAt(tblEditarCadastroProduto.getSelectedRow(), 0).toString());
                txtCodMaterial.setText(tblEditarCadastroProduto.getValueAt(tblEditarCadastroProduto.getSelectedRow(), 1).toString());
                txtMaterial.setText(tblEditarCadastroProduto.getValueAt(tblEditarCadastroProduto.getSelectedRow(), 2).toString());
                txtTipo.setText(tblEditarCadastroProduto.getValueAt(tblEditarCadastroProduto.getSelectedRow(), 3).toString());
                pnlProdutos.setEnabledAt(0, true);
                pnlProdutos.setEnabledAt(1, false);
                pnlProdutos.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_btnSelecionarProdutoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        pnlProdutos.setEnabledAt(0, true);
        pnlProdutos.setEnabledAt(1, false);
        pnlProdutos.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pnlProdutos.setEnabledAt(0, false);
        pnlProdutos.setEnabledAt(1, true);
        pnlProdutos.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalvarCadastroProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroProduto1ActionPerformed
        if (txtLoteProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lote inválido");
            txtLoteProduto.requestFocus();
        } else if (txtIdProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecionar Produto");
        } else if (cmbFinalidadeProduto.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Finalidade da Análise Inválida");
        } else if (txtEntradaProduto.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Data Inválida");
        } else if (novoEntradaProduto) {
            criarCadastroProduto();
        } else {
            atulizarCadastroProduto(idProduto);
        }
    }//GEN-LAST:event_btnSalvarCadastroProduto1ActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoteCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLoteCromatografo dialog = new FrmLoteCromatografo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFechar;
    public static javax.swing.JButton btnSalvarCadastroProduto1;
    private javax.swing.JButton btnSelecionarProduto;
    private javax.swing.JComboBox cmbFinalidadeProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlPesquisar;
    private javax.swing.JTabbedPane pnlProdutos;
    private javax.swing.JTable tblEditarCadastroProduto;
    private javax.swing.JTextField txtCodMaterial;
    private com.toedter.calendar.JDateChooser txtEntradaProduto;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtLoteProduto;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtObsProduto;
    private javax.swing.JTextField txtPesquisarCadastroProduto;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

    public final void readEditarCadastroProduto() {
        DefaultTableModel model = (DefaultTableModel) tblEditarCadastroProduto.getModel();
        MaterialDAO equipDao = new MaterialDAO();
        model.setNumRows(0);
        for (Material prod : equipDao.readMaterial()) {
            model.addRow(new Object[]{
                prod.getMaterial_id(),
                prod.getCod_material(),
                prod.getMaterial(),
                prod.getTipo(),
                prod.getCod_metodo(),
                prod.getMetodo().getMetodo_id()
            });
        }
    }

    public final void readFinalidadeProduto() {
        cmbFinalidadeProduto.removeAllItems();
        cmbFinalidadeProduto.addItem("");
        categoryMap.clear();
        AnaliseDAO anlsDao = new AnaliseDAO();
        for (Analise anls : anlsDao.readAnaliseFinalidade()) {
            Integer id = anls.getAnalise_finalidade_id();
            String name = anls.getAnalise_finalidade();
            cmbFinalidadeProduto.addItem(name);
            categoryMap.put(id, name);
        }
    }

    private void carregarDadosCadastroProduto(int id) {
        novoEntradaProduto = false;
        readEditarCadastroProduto();
        readFinalidadeProduto();
        Lote lot = new Lote();
        lot.setLote_id(id);
        LoteDAO lotDAO = new LoteDAO();
        lotDAO.selectLote(lot);
        txtLoteProduto.setText(lot.getLote_produto());
        txtIdProduto.setText(lot.getLote_id().toString());
        txtObsProduto.setText(lot.getLote_obs());
        txtCodMaterial.setText(lot.getProduto().getCod_material());
        txtMaterial.setText(lot.getProduto().getMaterial());
        txtTipo.setText(lot.getProduto().getTipo());
        txtEntradaProduto.setDate(DataHora.getTimestampDate(lot.getData_entrada()));
        String[] finalidade = {lot.getAnalise().getAnalise_finalidade()};
        cmbFinalidadeProduto.setSelectedItem(finalidade[0]);
        tblEditarCadastroProduto.setEnabled(false);
        txtPesquisarCadastroProduto.setEnabled(false);
    }

    private void abrirDados() {
        tblEditarCadastroProduto.setEnabled(true);
        limparCampos();
        novoEntradaProduto = true;
        txtEntradaProduto.setDate(new Date());
        readEditarCadastroProduto();
        readFinalidadeProduto();
    }

    private void fecharDados() {
        novoEntradaProduto = false;
        limparCampos();
        pnlProdutos.setEnabledAt(0, true);
        pnlProdutos.setEnabledAt(1, false);
        pnlProdutos.setSelectedIndex(0);
    }

    private void limparCampos() {
        txtCodMaterial.setText(null);
        txtEntradaProduto.setDate(null);
        txtLoteProduto.setText(null);
        txtLoteProduto.setText(null);
        txtMaterial.setText(null);
        txtObsProduto.setText(null);
        txtPesquisarCadastroProduto.setText(null);
        txtTipo.setText(null);
        txtIdProduto.setText(null);
        tblEditarCadastroProduto.setRowSorter(null);
    }

    private void criarCadastroProduto() {
        Lote lot = new Lote();
        LoteDAO lotDAO = new LoteDAO();
        try {
            Material prod = new Material();
            Analise alns = new Analise();
            prod.setMaterial_id(Integer.parseInt(txtIdProduto.getText()));
            alns.setAnalise_finalidade_id(ComboBox.getKeyForValue(cmbFinalidadeProduto.getSelectedItem().toString(), categoryMap));
            lot.setProduto(prod);
            lot.setAnalise(alns);
            lot.setLote_produto(txtLoteProduto.getText().toUpperCase());
            lot.setData_entrada(DataHora.getTimestampDate(txtEntradaProduto.getDate()));
            Calendar c = txtEntradaProduto.getCalendar();
            c.add(Calendar.DATE, +5);
            lot.setData_prevista(DataHora.getTimestampDate(c.getTime()));
            lot.setLote_obs(txtObsProduto.getText().toUpperCase());
            lotDAO.createLote(lot);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
        } finally {
            fecharDados();
        }
    }

    private void atulizarCadastroProduto(int lote_id) {
        Lote lot = new Lote();
        LoteDAO lotDAO = new LoteDAO();
        try {
            Material prod = new Material();
            prod.setMaterial_id(Integer.parseInt(txtIdProduto.getText()));
            Analise alns = new Analise();
            alns.setAnalise_finalidade_id(ComboBox.getKeyForValue(cmbFinalidadeProduto.getSelectedItem().toString(), categoryMap));
            lot.setLote_id(lote_id);
            lot.setProduto(prod);
            lot.setAnalise(alns);
            lot.setLote_produto(txtLoteProduto.getText().toUpperCase());
            lot.setData_entrada(DataHora.getTimestampDate(txtEntradaProduto.getDate()));
            Calendar c = txtEntradaProduto.getCalendar();
            c.add(Calendar.DATE, +5);
            lot.setData_prevista(DataHora.getTimestampDate(c.getTime()));
            lot.setLote_obs(txtObsProduto.getText().toUpperCase());
            lotDAO.updateLote(lot);
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Erro ao atualizar dados: " + e);
        } finally {
            fecharDados();
        }
    }

    private void deletarCadastroProduto(int lote_id) {
        Lote lot = new Lote();
        LoteDAO lotDAO = new LoteDAO();
        try {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Realmente deseja Excluir esse registro?", "Aviso", JOptionPane.YES_NO_OPTION);
            if (dialogResult == 0) {
                lot.setLote_id(lote_id);
                lotDAO.deleteLote(lot);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao atulalizar dados: " + e);
        } finally {
            fecharDados();
        }
    }

}
