/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package view.logbook;

import DAO.AnaliseDAO;
import DAO.CromatografoDAO;
import model.Analise;
import model.Cromatografo;
import util.ComboBox;
import java.util.TreeMap;
import javax.swing.JOptionPane;

/**
 *
 * @author rafael.lopes
 */
public class FrmNovoRegistro extends javax.swing.JDialog {

    private TreeMap<Integer, String> categoryMapAnaliseStatus = new TreeMap<>();
    private FrmLogCromatografo frm;
    private static String sys_name;

    /**
     * Creates new form FrmNovoRegistro
     *
     * @param parent
     * @param modal
     * @param system_name
     * @param LogCromatografo
     *
     */
    public FrmNovoRegistro(java.awt.Frame parent, boolean modal, FrmLogCromatografo LogCromatografo,
            String system_name) {
        super(parent, modal);
        initComponents();
        frm = LogCromatografo;
        sys_name = system_name;
        setLocationRelativeTo(null);
        setTitle("Novo Registro");
        this.setResizable(false);
        readAmaliseStatus();
        carregar();
    }

    public final void readAmaliseStatus() {
        cmbAnaliseStatus.removeAllItems();
        cmbAnaliseStatus.addItem("");
        categoryMapAnaliseStatus.clear();
        AnaliseDAO anseDao = new AnaliseDAO();
        for (Analise anls : anseDao.readAnaliseStatus()) {
            Integer id = anls.getAnalise_status_id();
            String name = anls.getAnalise_status();
            cmbAnaliseStatus.addItem(name);
            categoryMapAnaliseStatus.put(id, name);
        }
    }

    private void novoRegistro(String analise_status, String analise_tipo) {
        //Abre Dialog para savar
        FrmDialogSalvar frmSalvar = new FrmDialogSalvar(null, true, sys_name,
                analise_status, analise_tipo);
        frmSalvar.setVisible(true);
        if (FrmDialogSalvar.senha()) {
            dispose();
        }
    }

    private void carregar() {
        try {
            Cromatografo equip = new Cromatografo();
            CromatografoDAO equipDAO = new CromatografoDAO();
            equip.setSystem_name(sys_name);
            equipDAO.selectLogCromatografo(equip);
            if (equip.getAnalise().getAnalise_status_id() == 2) {
                btnFimAnalise.setEnabled(false);
                btnAguardando.setEnabled(false);
                btnAjusteSistema.setEnabled(false);
                btnAnalise.setEnabled(false);
                btnEstabilizacao.setEnabled(false);
                btnLimpeza.setEnabled(false);
                btnManutencao.setEnabled(false);
                btnOutro.setEnabled(false);
                cmbAnaliseStatus.setEnabled(false);
                btnFaseMovel.setEnabled(false);
                btnColuna.setEnabled(false);
                btnSystemSuitability.setEnabled(false);
            } else if (equip.getAnalise().getAnalise_status_id() == 1) {
                btnNovaAnalise.setEnabled(false);
                btnFimAnalise.setEnabled(false);
            } else {
                btnNovaAnalise.setEnabled(false);
                btnFimAnalise.setEnabled(true);
            }
        } catch (Exception e) {
            btnNovaAnalise.setEnabled(true);
            btnFimAnalise.setEnabled(false);
            btnAguardando.setEnabled(false);
            btnAjusteSistema.setEnabled(false);
            btnAnalise.setEnabled(false);
            btnEstabilizacao.setEnabled(false);
            btnLimpeza.setEnabled(false);
            btnManutencao.setEnabled(false);
            btnOutro.setEnabled(false);
            cmbAnaliseStatus.setEnabled(false);
            btnFaseMovel.setEnabled(false);
            btnColuna.setEnabled(false);
            btnSystemSuitability.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbAnaliseStatus = new javax.swing.JComboBox();
        btnOutro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAnalise = new javax.swing.JButton();
        btnAjusteSistema = new javax.swing.JButton();
        btnAguardando = new javax.swing.JButton();
        btnEstabilizacao = new javax.swing.JButton();
        btnLimpeza = new javax.swing.JButton();
        btnManutencao = new javax.swing.JButton();
        btnSystemSuitability = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnNovaAnalise = new javax.swing.JButton();
        btnFimAnalise = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnFaseMovel = new javax.swing.JButton();
        btnColuna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Outro"));

        cmbAnaliseStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnOutro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOutro.setText("Outro");
        btnOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbAnaliseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOutro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOutro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbAnaliseStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        btnAnalise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnalise.setText("Análise");
        btnAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnaliseActionPerformed(evt);
            }
        });

        btnAjusteSistema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAjusteSistema.setText("Ajuste do Sistema");
        btnAjusteSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjusteSistemaActionPerformed(evt);
            }
        });

        btnAguardando.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAguardando.setText("Aguardando");
        btnAguardando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAguardandoActionPerformed(evt);
            }
        });

        btnEstabilizacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEstabilizacao.setText("Estabilização");
        btnEstabilizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstabilizacaoActionPerformed(evt);
            }
        });

        btnLimpeza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpeza.setText("Limpeza");
        btnLimpeza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpezaActionPerformed(evt);
            }
        });

        btnManutencao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnManutencao.setText("Manutenção");
        btnManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManutencaoActionPerformed(evt);
            }
        });

        btnSystemSuitability.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSystemSuitability.setText("System Suitability");
        btnSystemSuitability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemSuitabilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManutencao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpeza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEstabilizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAguardando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjusteSistema, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(btnAnalise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSystemSuitability, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAjusteSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSystemSuitability, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAguardando, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstabilizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpeza, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Início / Fim"));

        btnNovaAnalise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNovaAnalise.setText("Nova Análise");
        btnNovaAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaAnaliseActionPerformed(evt);
            }
        });

        btnFimAnalise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFimAnalise.setText("Fim Análise");
        btnFimAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFimAnaliseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnNovaAnalise, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnFimAnalise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovaAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFimAnalise, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema"));

        btnFaseMovel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFaseMovel.setText("Fase Móvel");
        btnFaseMovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaseMovelActionPerformed(evt);
            }
        });

        btnColuna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnColuna.setText("Coluna");
        btnColuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFaseMovel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnColuna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFaseMovel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColuna, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstabilizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstabilizacaoActionPerformed
        novoRegistro("8", null);
    }//GEN-LAST:event_btnEstabilizacaoActionPerformed

    private void btnAjusteSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjusteSistemaActionPerformed
        novoRegistro("6", null);
    }//GEN-LAST:event_btnAjusteSistemaActionPerformed

    private void btnAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnaliseActionPerformed
        if (!FrmLogCromatografo.ckbColuna.isSelected()) {
            JOptionPane.showMessageDialog(null, "Coluna Cromatográfica não selecionada");
        } else if (!FrmLogCromatografo.ckbFaseMovel.isSelected()) {
            JOptionPane.showMessageDialog(null, "Fase Móvel não selecionada ou inválida");
        } else if (!FrmLogCromatografo.ckbSystem.isSelected()) {
            JOptionPane.showMessageDialog(null, "Sistema não está verificado");
        } else {
            novoRegistro("5", null);
        }
    }//GEN-LAST:event_btnAnaliseActionPerformed

    private void btnAguardandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAguardandoActionPerformed
        novoRegistro("7", null);
    }//GEN-LAST:event_btnAguardandoActionPerformed

    private void btnLimpezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpezaActionPerformed
        novoRegistro("9", null);
    }//GEN-LAST:event_btnLimpezaActionPerformed

    private void btnNovaAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaAnaliseActionPerformed
        FrmNovoRegistroCromatografo frmNovo = new FrmNovoRegistroCromatografo(null, true, sys_name);
        frmNovo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNovaAnaliseActionPerformed

    private void btnFimAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFimAnaliseActionPerformed
        novoRegistro("2", "FINAL ANÁLISE");
    }//GEN-LAST:event_btnFimAnaliseActionPerformed

    private void btnManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManutencaoActionPerformed
        novoRegistro("10", null);
    }//GEN-LAST:event_btnManutencaoActionPerformed

    private void btnOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroActionPerformed
        if (!cmbAnaliseStatus.getSelectedItem().toString().equals("")) {
            novoRegistro(String.valueOf(ComboBox.getKeyForValue(cmbAnaliseStatus.getSelectedItem().toString(),
                    categoryMapAnaliseStatus)), null);
        } else {
            JOptionPane.showMessageDialog(null, "Status da Análise inválida");
            cmbAnaliseStatus.requestFocus();
        }
    }//GEN-LAST:event_btnOutroActionPerformed

    private void btnFaseMovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaseMovelActionPerformed
        FrmFaseMovelCromatografo frmLogFM = new FrmFaseMovelCromatografo(null, true, sys_name);
        frmLogFM.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFaseMovelActionPerformed

    private void btnColunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColunaActionPerformed
        FrmColunaCromatografo frmCol = new FrmColunaCromatografo(null, true, sys_name);
        frmCol.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnColunaActionPerformed

    private void btnSystemSuitabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemSuitabilityActionPerformed
        FrmSystemCromatografo frmSystem = new FrmSystemCromatografo(null, true, sys_name);
        frmSystem.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSystemSuitabilityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNovoRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmNovoRegistro dialog = new FrmNovoRegistro(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAguardando;
    private javax.swing.JButton btnAjusteSistema;
    private javax.swing.JButton btnAnalise;
    private javax.swing.JButton btnColuna;
    private javax.swing.JButton btnEstabilizacao;
    private javax.swing.JButton btnFaseMovel;
    private javax.swing.JButton btnFimAnalise;
    private javax.swing.JButton btnLimpeza;
    private javax.swing.JButton btnManutencao;
    private javax.swing.JButton btnNovaAnalise;
    private javax.swing.JButton btnOutro;
    private javax.swing.JButton btnSystemSuitability;
    private javax.swing.JComboBox cmbAnaliseStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
