/*
 * Copyright (C) 2017 rafael.lopes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package view.logbook;

import DAO.CromatografoDAO;
import DAO.SystemSuitabilityDAO;
import model.Cromatografo;
import model.SystemSuitability;
import model.Usuario;
import util.DataHora;
import view.config.FrmSelecionaUsuario;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author rafael.lopes
 */
public class FrmSystemCromatografo extends javax.swing.JDialog {

    private static String sys_name;

    /**
     * Creates new form FrmNovoRegistroCromatografo
     *
     * @param parent
     * @param modal
     * @param system_name
     */
    public FrmSystemCromatografo(java.awt.Frame parent, boolean modal, String system_name) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Nova Campanha - " + system_name);
        sys_name = system_name;
        if (btnCancelar.isVisible()) {
            btnAguardando.setVisible(false);
        }
        loadSolucao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDados = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtDescricaoSolucao1 = new javax.swing.JTextField();
        cmbSolucao1 = new javax.swing.JComboBox();
        txtNumeroSolucao1 = new javax.swing.JSpinner();
        btnUsuarioSolucao1 = new javax.swing.JButton();
        txtUserSolucao1 = new javax.swing.JTextField();
        txtDataSolucao1 = new com.toedter.calendar.JDateChooser();
        cmbSolucao2 = new javax.swing.JComboBox();
        txtNumeroSolucao2 = new javax.swing.JSpinner();
        txtDescricaoSolucao2 = new javax.swing.JTextField();
        txtDataSolucao2 = new com.toedter.calendar.JDateChooser();
        txtUserSolucao2 = new javax.swing.JTextField();
        btnUsuarioSolucao2 = new javax.swing.JButton();
        cmbSolucao3 = new javax.swing.JComboBox();
        txtNumeroSolucao3 = new javax.swing.JSpinner();
        txtDescricaoSolucao3 = new javax.swing.JTextField();
        txtDataSolucao3 = new com.toedter.calendar.JDateChooser();
        txtUserSolucao3 = new javax.swing.JTextField();
        btnUsuarioSolucao3 = new javax.swing.JButton();
        cmbSolucao4 = new javax.swing.JComboBox();
        txtNumeroSolucao4 = new javax.swing.JSpinner();
        txtDescricaoSolucao4 = new javax.swing.JTextField();
        txtDataSolucao4 = new com.toedter.calendar.JDateChooser();
        txtUserSolucao4 = new javax.swing.JTextField();
        btnUsuarioSolucao4 = new javax.swing.JButton();
        cmbSolucao5 = new javax.swing.JComboBox();
        txtNumeroSolucao5 = new javax.swing.JSpinner();
        txtDescricaoSolucao5 = new javax.swing.JTextField();
        txtDataSolucao5 = new com.toedter.calendar.JDateChooser();
        txtUserSolucao5 = new javax.swing.JTextField();
        btnUsuarioSolucao5 = new javax.swing.JButton();
        cmbSolucao6 = new javax.swing.JComboBox();
        txtNumeroSolucao6 = new javax.swing.JSpinner();
        txtDescricaoSolucao6 = new javax.swing.JTextField();
        txtDataSolucao6 = new com.toedter.calendar.JDateChooser();
        txtUserSolucao6 = new javax.swing.JTextField();
        btnUsuarioSolucao6 = new javax.swing.JButton();
        cmbSolucao7 = new javax.swing.JComboBox();
        txtNumeroSolucao7 = new javax.swing.JSpinner();
        txtDescricaoSolucao7 = new javax.swing.JTextField();
        txtDataSolucao7 = new com.toedter.calendar.JDateChooser();
        txtUserSolucao7 = new javax.swing.JTextField();
        btnUsuarioSolucao7 = new javax.swing.JButton();
        cmbSolucao8 = new javax.swing.JComboBox();
        txtNumeroSolucao8 = new javax.swing.JSpinner();
        txtDescricaoSolucao8 = new javax.swing.JTextField();
        txtDataSolucao8 = new com.toedter.calendar.JDateChooser();
        txtUserSolucao8 = new javax.swing.JTextField();
        btnUsuarioSolucao8 = new javax.swing.JButton();
        cmbSolucao9 = new javax.swing.JComboBox();
        txtNumeroSolucao9 = new javax.swing.JSpinner();
        txtDescricaoSolucao9 = new javax.swing.JTextField();
        txtDataSolucao9 = new com.toedter.calendar.JDateChooser();
        txtUserSolucao9 = new javax.swing.JTextField();
        btnUsuarioSolucao9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAguardando = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Metodologia"));

        txtDescricaoSolucao1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbSolucao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSolucao1ActionPerformed(evt);
            }
        });

        btnUsuarioSolucao1.setText("Usuário");
        btnUsuarioSolucao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioSolucao1ActionPerformed(evt);
            }
        });

        txtUserSolucao1.setEditable(false);
        txtUserSolucao1.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbSolucao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSolucao2ActionPerformed(evt);
            }
        });

        txtDescricaoSolucao2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao2.setEditable(false);
        txtUserSolucao2.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUsuarioSolucao2.setText("Usuário");
        btnUsuarioSolucao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioSolucao2ActionPerformed(evt);
            }
        });

        cmbSolucao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSolucao3ActionPerformed(evt);
            }
        });

        txtDescricaoSolucao3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao3.setEditable(false);
        txtUserSolucao3.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUsuarioSolucao3.setText("Usuário");
        btnUsuarioSolucao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioSolucao3ActionPerformed(evt);
            }
        });

        cmbSolucao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSolucao4ActionPerformed(evt);
            }
        });

        txtDescricaoSolucao4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao4.setEditable(false);
        txtUserSolucao4.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUsuarioSolucao4.setText("Usuário");
        btnUsuarioSolucao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioSolucao4ActionPerformed(evt);
            }
        });

        cmbSolucao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSolucao5ActionPerformed(evt);
            }
        });

        txtDescricaoSolucao5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao5.setEditable(false);
        txtUserSolucao5.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUsuarioSolucao5.setText("Usuário");
        btnUsuarioSolucao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioSolucao5ActionPerformed(evt);
            }
        });

        cmbSolucao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSolucao6ActionPerformed(evt);
            }
        });

        txtDescricaoSolucao6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao6.setEditable(false);
        txtUserSolucao6.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUsuarioSolucao6.setText("Usuário");
        btnUsuarioSolucao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioSolucao6ActionPerformed(evt);
            }
        });

        cmbSolucao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSolucao7ActionPerformed(evt);
            }
        });

        txtDescricaoSolucao7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao7.setEditable(false);
        txtUserSolucao7.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUsuarioSolucao7.setText("Usuário");
        btnUsuarioSolucao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioSolucao7ActionPerformed(evt);
            }
        });

        cmbSolucao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSolucao8ActionPerformed(evt);
            }
        });

        txtDescricaoSolucao8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao8.setEditable(false);
        txtUserSolucao8.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUsuarioSolucao8.setText("Usuário");
        btnUsuarioSolucao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioSolucao8ActionPerformed(evt);
            }
        });

        cmbSolucao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSolucao9ActionPerformed(evt);
            }
        });

        txtDescricaoSolucao9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtUserSolucao9.setEditable(false);
        txtUserSolucao9.setBackground(new java.awt.Color(204, 204, 204));
        txtUserSolucao9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUsuarioSolucao9.setText("Usuário");
        btnUsuarioSolucao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioSolucao9ActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Solução");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nº");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Descrição");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Fabricação");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Responsável");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSolucao2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioSolucao2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSolucao3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioSolucao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSolucao4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioSolucao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSolucao5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioSolucao5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSolucao6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioSolucao6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSolucao7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioSolucao7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSolucao8, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioSolucao8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSolucao9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioSolucao9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(cmbSolucao1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroSolucao1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(txtDescricaoSolucao1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataSolucao1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserSolucao1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsuarioSolucao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuarioSolucao1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoSolucao1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserSolucao1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDataSolucao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSolucao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSolucao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuarioSolucao2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoSolucao2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserSolucao2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSolucao2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSolucao2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuarioSolucao3)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoSolucao3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserSolucao3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSolucao3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSolucao3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuarioSolucao4)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoSolucao4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserSolucao4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSolucao4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSolucao4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuarioSolucao5)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoSolucao5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserSolucao5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSolucao5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSolucao5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuarioSolucao6)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoSolucao6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserSolucao6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSolucao6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSolucao6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuarioSolucao7)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoSolucao7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserSolucao7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSolucao7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSolucao7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuarioSolucao8)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoSolucao8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserSolucao8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSolucao8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSolucao8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuarioSolucao9)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescricaoSolucao9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserSolucao9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataSolucao9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cmbSolucao9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSolucao9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Fechar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAguardando.setText("Aguardando");
        btnAguardando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAguardandoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                        .addComponent(btnAguardando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar)
                        .addComponent(btnAguardando)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlDados);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioSolucao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioSolucao1ActionPerformed
        Usuario user = new Usuario();
        FrmSelecionaUsuario frm = new FrmSelecionaUsuario(null, true, user);
        frm.setVisible(true);
        txtUserSolucao1.setText(user.getUser());
    }//GEN-LAST:event_btnUsuarioSolucao1ActionPerformed

    private void btnUsuarioSolucao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioSolucao2ActionPerformed
        Usuario user = new Usuario();
        FrmSelecionaUsuario frm = new FrmSelecionaUsuario(null, true, user);
        frm.setVisible(true);
        txtUserSolucao2.setText(user.getUser());
    }//GEN-LAST:event_btnUsuarioSolucao2ActionPerformed

    private void btnUsuarioSolucao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioSolucao3ActionPerformed
        Usuario user = new Usuario();
        FrmSelecionaUsuario frm = new FrmSelecionaUsuario(null, true, user);
        frm.setVisible(true);
        txtUserSolucao3.setText(user.getUser());
    }//GEN-LAST:event_btnUsuarioSolucao3ActionPerformed

    private void btnUsuarioSolucao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioSolucao4ActionPerformed
        Usuario user = new Usuario();
        FrmSelecionaUsuario frm = new FrmSelecionaUsuario(null, true, user);
        frm.setVisible(true);
        txtUserSolucao4.setText(user.getUser());
    }//GEN-LAST:event_btnUsuarioSolucao4ActionPerformed

    private void btnUsuarioSolucao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioSolucao5ActionPerformed
        Usuario user = new Usuario();
        FrmSelecionaUsuario frm = new FrmSelecionaUsuario(null, true, user);
        frm.setVisible(true);
        txtUserSolucao5.setText(user.getUser());
    }//GEN-LAST:event_btnUsuarioSolucao5ActionPerformed

    private void btnUsuarioSolucao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioSolucao6ActionPerformed
        Usuario user = new Usuario();
        FrmSelecionaUsuario frm = new FrmSelecionaUsuario(null, true, user);
        frm.setVisible(true);
        txtUserSolucao6.setText(user.getUser());
    }//GEN-LAST:event_btnUsuarioSolucao6ActionPerformed

    private void btnUsuarioSolucao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioSolucao7ActionPerformed
        Usuario user = new Usuario();
        FrmSelecionaUsuario frm = new FrmSelecionaUsuario(null, true, user);
        frm.setVisible(true);
        txtUserSolucao7.setText(user.getUser());
    }//GEN-LAST:event_btnUsuarioSolucao7ActionPerformed

    private void btnUsuarioSolucao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioSolucao8ActionPerformed
        Usuario user = new Usuario();
        FrmSelecionaUsuario frm = new FrmSelecionaUsuario(null, true, user);
        frm.setVisible(true);
        txtUserSolucao8.setText(user.getUser());
    }//GEN-LAST:event_btnUsuarioSolucao8ActionPerformed

    private void btnUsuarioSolucao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioSolucao9ActionPerformed
        Usuario user = new Usuario();
        FrmSelecionaUsuario frm = new FrmSelecionaUsuario(null, true, user);
        frm.setVisible(true);
        txtUserSolucao9.setText(user.getUser());
    }//GEN-LAST:event_btnUsuarioSolucao9ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            if (cmbSolucao1.getSelectedItem().toString().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione uma Solução 1");
                cmbSolucao1.requestFocus();
            } else if (!cmbSolucao1.getSelectedItem().toString().isEmpty()
                    && ((Integer) txtNumeroSolucao1.getValue() == 0
                    || txtDescricaoSolucao1.getText().isEmpty()
                    || txtDataSolucao1.getDate() == null
                    || txtUserSolucao1.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Campos da Solução 1 inválidos");
            } else if (!cmbSolucao2.getSelectedItem().toString().isEmpty()
                    && ((Integer) txtNumeroSolucao2.getValue() == 0
                    || txtDescricaoSolucao2.getText().isEmpty()
                    || txtDataSolucao2.getDate() == null
                    || txtUserSolucao2.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Campos da Solução 2 inválidos");
            } else if (!cmbSolucao3.getSelectedItem().toString().isEmpty()
                    && ((Integer) txtNumeroSolucao3.getValue() == 0
                    || txtDescricaoSolucao3.getText().isEmpty()
                    || txtDataSolucao3.getDate() == null
                    || txtUserSolucao3.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Campos da Solução 3 inválidos");
            } else if (!cmbSolucao4.getSelectedItem().toString().isEmpty()
                    && ((Integer) txtNumeroSolucao4.getValue() == 0
                    || txtDescricaoSolucao4.getText().isEmpty()
                    || txtDataSolucao4.getDate() == null
                    || txtUserSolucao4.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Campos da Solução 4 inválidos");
            } else if (!cmbSolucao5.getSelectedItem().toString().isEmpty()
                    && ((Integer) txtNumeroSolucao5.getValue() == 0
                    || txtDescricaoSolucao5.getText().isEmpty()
                    || txtDataSolucao5.getDate() == null
                    || txtUserSolucao5.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Campos da Solução 5 inválidos");
            } else if (!cmbSolucao6.getSelectedItem().toString().isEmpty()
                    && ((Integer) txtNumeroSolucao6.getValue() == 0
                    || txtDescricaoSolucao6.getText().isEmpty()
                    || txtDataSolucao6.getDate() == null
                    || txtUserSolucao6.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Campos da Solução 6 inválidos");
            } else if (!cmbSolucao7.getSelectedItem().toString().isEmpty()
                    && ((Integer) txtNumeroSolucao7.getValue() == 0
                    || txtDescricaoSolucao7.getText().isEmpty()
                    || txtDataSolucao7.getDate() == null
                    || txtUserSolucao7.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Campos da Solução 7 inválidos");
            } else if (!cmbSolucao8.getSelectedItem().toString().isEmpty()) {
                if ((Integer) txtNumeroSolucao8.getValue() == 0
                        || txtDescricaoSolucao8.getText().isEmpty()
                        || txtDataSolucao8.getDate() == null
                        || txtUserSolucao8.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Campos da Solução 8 inválidos");
                }
            } else if (!cmbSolucao9.getSelectedItem().toString().isEmpty()
                    && ((Integer) txtNumeroSolucao9.getValue() == 0
                    || txtDescricaoSolucao9.getText().isEmpty()
                    || txtDataSolucao9.getDate() == null
                    || txtUserSolucao9.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Campos da Solução 9 inválidos");
            } else {
                //Envia Codigo de Coluna
                String analise_status = "6";
                //Seleciona o Equipamento
                Cromatografo equip = new Cromatografo();
                CromatografoDAO equipDAO = new CromatografoDAO();
                equip.setSystem_name(sys_name);
                equipDAO.selectEquipamentoByName(equip);
                //Abre Dialog para savar
                FrmDialogSalvar frmSalvar = new FrmDialogSalvar(null, true, sys_name,
                        analise_status, "SYSTEM SUITABILITY");
                frmSalvar.setVisible(true);
                if (FrmDialogSalvar.senha()) {
                    criarSystem();
                    dispose();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possivel salvar. Algum Campo está inválido!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cmbSolucao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSolucao1ActionPerformed
        if (cmbSolucao1.getSelectedItem().toString().isEmpty()) {
            txtNumeroSolucao1.setEnabled(false);
            txtDescricaoSolucao1.setEnabled(false);
            txtDataSolucao1.setEnabled(false);
            txtUserSolucao1.setEnabled(false);
            btnUsuarioSolucao1.setEnabled(false);
        } else {
            txtNumeroSolucao1.setEnabled(true);
            txtDescricaoSolucao1.setEnabled(true);
            txtDataSolucao1.setEnabled(true);
            txtUserSolucao1.setEnabled(true);
            btnUsuarioSolucao1.setEnabled(true);
        }
    }//GEN-LAST:event_cmbSolucao1ActionPerformed

    private void cmbSolucao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSolucao2ActionPerformed
        if (cmbSolucao2.getSelectedItem().toString().isEmpty()) {
            txtNumeroSolucao2.setEnabled(false);
            txtDescricaoSolucao2.setEnabled(false);
            txtDataSolucao2.setEnabled(false);
            txtUserSolucao2.setEnabled(false);
            btnUsuarioSolucao2.setEnabled(false);
        } else {
            txtNumeroSolucao2.setEnabled(true);
            txtDescricaoSolucao2.setEnabled(true);
            txtDataSolucao2.setEnabled(true);
            txtUserSolucao2.setEnabled(true);
            btnUsuarioSolucao2.setEnabled(true);
        }
    }//GEN-LAST:event_cmbSolucao2ActionPerformed

    private void cmbSolucao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSolucao3ActionPerformed
        if (cmbSolucao3.getSelectedItem().toString().isEmpty()) {
            txtNumeroSolucao3.setEnabled(false);
            txtDescricaoSolucao3.setEnabled(false);
            txtDataSolucao3.setEnabled(false);
            txtUserSolucao3.setEnabled(false);
            btnUsuarioSolucao3.setEnabled(false);
        } else {
            txtNumeroSolucao3.setEnabled(true);
            txtDescricaoSolucao3.setEnabled(true);
            txtDataSolucao3.setEnabled(true);
            txtUserSolucao3.setEnabled(true);
            btnUsuarioSolucao3.setEnabled(true);
        }
    }//GEN-LAST:event_cmbSolucao3ActionPerformed

    private void cmbSolucao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSolucao4ActionPerformed
        if (cmbSolucao4.getSelectedItem().toString().isEmpty()) {
            txtNumeroSolucao4.setEnabled(false);
            txtDescricaoSolucao4.setEnabled(false);
            txtDataSolucao4.setEnabled(false);
            txtUserSolucao4.setEnabled(false);
            btnUsuarioSolucao4.setEnabled(false);
        } else {
            txtNumeroSolucao4.setEnabled(true);
            txtDescricaoSolucao4.setEnabled(true);
            txtDataSolucao4.setEnabled(true);
            txtUserSolucao4.setEnabled(true);
            btnUsuarioSolucao4.setEnabled(true);
        }
    }//GEN-LAST:event_cmbSolucao4ActionPerformed

    private void cmbSolucao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSolucao5ActionPerformed
        if (cmbSolucao5.getSelectedItem().toString().isEmpty()) {
            txtNumeroSolucao5.setEnabled(false);
            txtDescricaoSolucao5.setEnabled(false);
            txtDataSolucao5.setEnabled(false);
            txtUserSolucao5.setEnabled(false);
            btnUsuarioSolucao5.setEnabled(false);
        } else {
            txtNumeroSolucao5.setEnabled(true);
            txtDescricaoSolucao5.setEnabled(true);
            txtDataSolucao5.setEnabled(true);
            txtUserSolucao5.setEnabled(true);
            btnUsuarioSolucao5.setEnabled(true);
        }
    }//GEN-LAST:event_cmbSolucao5ActionPerformed

    private void cmbSolucao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSolucao6ActionPerformed
        if (cmbSolucao6.getSelectedItem().toString().isEmpty()) {
            txtNumeroSolucao6.setEnabled(false);
            txtDescricaoSolucao6.setEnabled(false);
            txtDataSolucao6.setEnabled(false);
            txtUserSolucao6.setEnabled(false);
            btnUsuarioSolucao6.setEnabled(false);
        } else {
            txtNumeroSolucao6.setEnabled(true);
            txtDescricaoSolucao6.setEnabled(true);
            txtDataSolucao6.setEnabled(true);
            txtUserSolucao6.setEnabled(true);
            btnUsuarioSolucao6.setEnabled(true);
        }
    }//GEN-LAST:event_cmbSolucao6ActionPerformed

    private void cmbSolucao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSolucao7ActionPerformed
        if (cmbSolucao7.getSelectedItem().toString().isEmpty()) {
            txtNumeroSolucao7.setEnabled(false);
            txtDescricaoSolucao7.setEnabled(false);
            txtDataSolucao7.setEnabled(false);
            txtUserSolucao7.setEnabled(false);
            btnUsuarioSolucao7.setEnabled(false);
        } else {
            txtNumeroSolucao7.setEnabled(true);
            txtDescricaoSolucao7.setEnabled(true);
            txtDataSolucao7.setEnabled(true);
            txtUserSolucao7.setEnabled(true);
            btnUsuarioSolucao7.setEnabled(true);
        }
    }//GEN-LAST:event_cmbSolucao7ActionPerformed

    private void cmbSolucao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSolucao8ActionPerformed
        if (cmbSolucao8.getSelectedItem().toString().isEmpty()) {
            txtNumeroSolucao8.setEnabled(false);
            txtDescricaoSolucao8.setEnabled(false);
            txtDataSolucao8.setEnabled(false);
            txtUserSolucao8.setEnabled(false);
            btnUsuarioSolucao8.setEnabled(false);
        } else {
            txtNumeroSolucao8.setEnabled(true);
            txtDescricaoSolucao8.setEnabled(true);
            txtDataSolucao8.setEnabled(true);
            txtUserSolucao8.setEnabled(true);
            btnUsuarioSolucao8.setEnabled(true);
        }
    }//GEN-LAST:event_cmbSolucao8ActionPerformed

    private void cmbSolucao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSolucao9ActionPerformed
        if (cmbSolucao9.getSelectedItem().toString().isEmpty()) {
            txtNumeroSolucao9.setEnabled(false);
            txtDescricaoSolucao9.setEnabled(false);
            txtDataSolucao9.setEnabled(false);
            txtUserSolucao9.setEnabled(false);
            btnUsuarioSolucao9.setEnabled(false);
        } else {
            txtNumeroSolucao9.setEnabled(true);
            txtDescricaoSolucao9.setEnabled(true);
            txtDataSolucao9.setEnabled(true);
            txtUserSolucao9.setEnabled(true);
            btnUsuarioSolucao9.setEnabled(true);
        }
    }//GEN-LAST:event_cmbSolucao9ActionPerformed

    private void btnAguardandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAguardandoActionPerformed
        //Envia Codigo de Coluna
        String analise_status = "7";
        //Seleciona o Equipamento
        Cromatografo equip = new Cromatografo();
        CromatografoDAO equipDAO = new CromatografoDAO();
        equip.setSystem_name(sys_name);
        equipDAO.selectEquipamentoByName(equip);
        //Abre Dialog para savar
        FrmDialogSalvar frmSalvar = new FrmDialogSalvar(null, true, sys_name,
                analise_status, "SYSTEM SUITABILITY");
        frmSalvar.setVisible(true);
        if (FrmDialogSalvar.senha()) {
            criarSystem();
            dispose();
        }
    }//GEN-LAST:event_btnAguardandoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSystemCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSystemCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSystemCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSystemCromatografo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmSystemCromatografo dialog = new FrmSystemCromatografo(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAguardando;
    public static javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUsuarioSolucao1;
    private javax.swing.JButton btnUsuarioSolucao2;
    private javax.swing.JButton btnUsuarioSolucao3;
    private javax.swing.JButton btnUsuarioSolucao4;
    private javax.swing.JButton btnUsuarioSolucao5;
    private javax.swing.JButton btnUsuarioSolucao6;
    private javax.swing.JButton btnUsuarioSolucao7;
    private javax.swing.JButton btnUsuarioSolucao8;
    private javax.swing.JButton btnUsuarioSolucao9;
    private javax.swing.JComboBox cmbSolucao1;
    private javax.swing.JComboBox cmbSolucao2;
    private javax.swing.JComboBox cmbSolucao3;
    private javax.swing.JComboBox cmbSolucao4;
    private javax.swing.JComboBox cmbSolucao5;
    private javax.swing.JComboBox cmbSolucao6;
    private javax.swing.JComboBox cmbSolucao7;
    private javax.swing.JComboBox cmbSolucao8;
    private javax.swing.JComboBox cmbSolucao9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlDados;
    private com.toedter.calendar.JDateChooser txtDataSolucao1;
    private com.toedter.calendar.JDateChooser txtDataSolucao2;
    private com.toedter.calendar.JDateChooser txtDataSolucao3;
    private com.toedter.calendar.JDateChooser txtDataSolucao4;
    private com.toedter.calendar.JDateChooser txtDataSolucao5;
    private com.toedter.calendar.JDateChooser txtDataSolucao6;
    private com.toedter.calendar.JDateChooser txtDataSolucao7;
    private com.toedter.calendar.JDateChooser txtDataSolucao8;
    private com.toedter.calendar.JDateChooser txtDataSolucao9;
    private javax.swing.JTextField txtDescricaoSolucao1;
    private javax.swing.JTextField txtDescricaoSolucao2;
    private javax.swing.JTextField txtDescricaoSolucao3;
    private javax.swing.JTextField txtDescricaoSolucao4;
    private javax.swing.JTextField txtDescricaoSolucao5;
    private javax.swing.JTextField txtDescricaoSolucao6;
    private javax.swing.JTextField txtDescricaoSolucao7;
    private javax.swing.JTextField txtDescricaoSolucao8;
    private javax.swing.JTextField txtDescricaoSolucao9;
    private javax.swing.JSpinner txtNumeroSolucao1;
    private javax.swing.JSpinner txtNumeroSolucao2;
    private javax.swing.JSpinner txtNumeroSolucao3;
    private javax.swing.JSpinner txtNumeroSolucao4;
    private javax.swing.JSpinner txtNumeroSolucao5;
    private javax.swing.JSpinner txtNumeroSolucao6;
    private javax.swing.JSpinner txtNumeroSolucao7;
    private javax.swing.JSpinner txtNumeroSolucao8;
    private javax.swing.JSpinner txtNumeroSolucao9;
    private javax.swing.JTextField txtUserSolucao1;
    private javax.swing.JTextField txtUserSolucao2;
    private javax.swing.JTextField txtUserSolucao3;
    private javax.swing.JTextField txtUserSolucao4;
    private javax.swing.JTextField txtUserSolucao5;
    private javax.swing.JTextField txtUserSolucao6;
    private javax.swing.JTextField txtUserSolucao7;
    private javax.swing.JTextField txtUserSolucao8;
    private javax.swing.JTextField txtUserSolucao9;
    // End of variables declaration//GEN-END:variables

    private void loadSolucao() {
        loadSolucao1();
        loadSolucao2();
        loadSolucao3();
        loadSolucao4();
        loadSolucao5();
        loadSolucao6();
        loadSolucao7();
        loadSolucao8();
        loadSolucao9();
        txtNumeroSolucao1.setModel(new SpinnerNumberModel(0, 0, 9, 1));
        txtNumeroSolucao2.setModel(new SpinnerNumberModel(0, 0, 9, 1));
        txtNumeroSolucao3.setModel(new SpinnerNumberModel(0, 0, 9, 1));
        txtNumeroSolucao4.setModel(new SpinnerNumberModel(0, 0, 9, 1));
        txtNumeroSolucao5.setModel(new SpinnerNumberModel(0, 0, 9, 1));
        txtNumeroSolucao6.setModel(new SpinnerNumberModel(0, 0, 9, 1));
        txtNumeroSolucao7.setModel(new SpinnerNumberModel(0, 0, 9, 1));
        txtNumeroSolucao8.setModel(new SpinnerNumberModel(0, 0, 9, 1));
        txtNumeroSolucao9.setModel(new SpinnerNumberModel(0, 0, 9, 1));
        Date date = new Date();
        txtDataSolucao1.setMaxSelectableDate(date);
        txtDataSolucao2.setMaxSelectableDate(date);
        txtDataSolucao3.setMaxSelectableDate(date);
        txtDataSolucao4.setMaxSelectableDate(date);
        txtDataSolucao5.setMaxSelectableDate(date);
        txtDataSolucao6.setMaxSelectableDate(date);
        txtDataSolucao7.setMaxSelectableDate(date);
        txtDataSolucao8.setMaxSelectableDate(date);
        txtDataSolucao9.setMaxSelectableDate(date);
    }

    private void loadSolucao1() {
        cmbSolucao1.removeAllItems();
        cmbSolucao1.addItem("");
        cmbSolucao1.addItem("Solução Padrão");
        cmbSolucao1.addItem("Solução System");
        cmbSolucao1.addItem("Solução Resolução");
        cmbSolucao1.addItem("Solução Referência");
        cmbSolucao1.addItem("Solução Sensibilidade");
        cmbSolucao1.addItem("Solução Teste");
        cmbSolucao1.addItem("Solução Concentrada");
        cmbSolucao1.addItem("Solução Diluída");
    }

    private void loadSolucao2() {
        cmbSolucao2.removeAllItems();
        cmbSolucao2.addItem("");
        cmbSolucao2.addItem("Solução Padrão");
        cmbSolucao2.addItem("Solução System");
        cmbSolucao2.addItem("Solução Resolução");
        cmbSolucao2.addItem("Solução Referência");
        cmbSolucao2.addItem("Solução Sensibilidade");
        cmbSolucao2.addItem("Solução Teste");
        cmbSolucao2.addItem("Solução Concentrada");
        cmbSolucao2.addItem("Solução Diluída");
    }

    private void loadSolucao3() {
        cmbSolucao3.removeAllItems();
        cmbSolucao3.addItem("");
        cmbSolucao3.addItem("Solução Padrão");
        cmbSolucao3.addItem("Solução System");
        cmbSolucao3.addItem("Solução Resolução");
        cmbSolucao3.addItem("Solução Referência");
        cmbSolucao3.addItem("Solução Sensibilidade");
        cmbSolucao3.addItem("Solução Teste");
        cmbSolucao3.addItem("Solução Concentrada");
        cmbSolucao3.addItem("Solução Diluída");
    }

    private void loadSolucao4() {
        cmbSolucao4.removeAllItems();
        cmbSolucao4.addItem("");
        cmbSolucao4.addItem("Solução Padrão");
        cmbSolucao4.addItem("Solução System");
        cmbSolucao4.addItem("Solução Resolução");
        cmbSolucao4.addItem("Solução Referência");
        cmbSolucao4.addItem("Solução Sensibilidade");
        cmbSolucao4.addItem("Solução Teste");
        cmbSolucao4.addItem("Solução Concentrada");
        cmbSolucao4.addItem("Solução Diluída");
    }

    private void loadSolucao5() {
        cmbSolucao5.removeAllItems();
        cmbSolucao5.addItem("");
        cmbSolucao5.addItem("Solução Padrão");
        cmbSolucao5.addItem("Solução System");
        cmbSolucao5.addItem("Solução Resolução");
        cmbSolucao5.addItem("Solução Referência");
        cmbSolucao5.addItem("Solução Sensibilidade");
        cmbSolucao5.addItem("Solução Teste");
        cmbSolucao5.addItem("Solução Concentrada");
        cmbSolucao5.addItem("Solução Diluída");
    }

    private void loadSolucao6() {
        cmbSolucao6.removeAllItems();
        cmbSolucao6.addItem("");
        cmbSolucao6.addItem("Solução Padrão");
        cmbSolucao6.addItem("Solução System");
        cmbSolucao6.addItem("Solução Resolução");
        cmbSolucao6.addItem("Solução Referência");
        cmbSolucao6.addItem("Solução Sensibilidade");
        cmbSolucao6.addItem("Solução Teste");
        cmbSolucao6.addItem("Solução Concentrada");
        cmbSolucao6.addItem("Solução Diluída");
    }

    private void loadSolucao7() {
        cmbSolucao7.removeAllItems();
        cmbSolucao7.addItem("");
        cmbSolucao7.addItem("Solução Padrão");
        cmbSolucao7.addItem("Solução System");
        cmbSolucao7.addItem("Solução Resolução");
        cmbSolucao7.addItem("Solução Referência");
        cmbSolucao7.addItem("Solução Sensibilidade");
        cmbSolucao7.addItem("Solução Teste");
        cmbSolucao7.addItem("Solução Concentrada");
        cmbSolucao7.addItem("Solução Diluída");
    }

    private void loadSolucao8() {
        cmbSolucao8.removeAllItems();
        cmbSolucao8.addItem("");
        cmbSolucao8.addItem("Solução Padrão");
        cmbSolucao8.addItem("Solução System");
        cmbSolucao8.addItem("Solução Resolução");
        cmbSolucao8.addItem("Solução Referência");
        cmbSolucao8.addItem("Solução Sensibilidade");
        cmbSolucao8.addItem("Solução Teste");
        cmbSolucao8.addItem("Solução Concentrada");
        cmbSolucao8.addItem("Solução Diluída");
    }

    private void loadSolucao9() {
        cmbSolucao9.removeAllItems();
        cmbSolucao9.addItem("");
        cmbSolucao9.addItem("Solução Padrão");
        cmbSolucao9.addItem("Solução System");
        cmbSolucao9.addItem("Solução Resolução");
        cmbSolucao9.addItem("Solução Referência");
        cmbSolucao9.addItem("Solução Sensibilidade");
        cmbSolucao9.addItem("Solução Teste");
        cmbSolucao9.addItem("Solução Concentrada");
        cmbSolucao9.addItem("Solução Diluída");
    }

    private void criarSystem() {
        try {
            SystemSuitability system = new SystemSuitability();
            SystemSuitabilityDAO systemDAO = new SystemSuitabilityDAO();
            Cromatografo equip = new Cromatografo();
            equip.setSystem_name(sys_name);
            system.setCromatografo(equip);
            system.setSolucao_1(cmbSolucao1.getSelectedItem().toString());
            system.setNumero_solucao_1((int) txtNumeroSolucao1.getValue());
            system.setDescricao_solucao_1(txtDescricaoSolucao1.getText());
            system.setData_solucao_1(DataHora.getTimestampDate(txtDataSolucao1.getDate()));
            Usuario user1 = new Usuario();
            user1.setUser(txtUserSolucao1.getText());
            system.setUser_solucao_1(user1);
            system.setSolucao_2(cmbSolucao2.getSelectedItem().toString());
            system.setNumero_solucao_2((int) txtNumeroSolucao2.getValue());
            system.setDescricao_solucao_2(txtDescricaoSolucao2.getText());
            system.setData_solucao_2(DataHora.getTimestampDate(txtDataSolucao2.getDate()));
            Usuario user2 = new Usuario();
            user2.setUser(txtUserSolucao2.getText());
            system.setUser_solucao_2(user2);
            system.setSolucao_3(cmbSolucao3.getSelectedItem().toString());
            system.setNumero_solucao_3((int) txtNumeroSolucao3.getValue());
            system.setDescricao_solucao_3(txtDescricaoSolucao3.getText());
            system.setData_solucao_3(DataHora.getTimestampDate(txtDataSolucao3.getDate()));
            Usuario user3 = new Usuario();
            user3.setUser(txtUserSolucao3.getText());
            system.setUser_solucao_3(user3);
            system.setSolucao_4(cmbSolucao4.getSelectedItem().toString());
            system.setNumero_solucao_4((int) txtNumeroSolucao4.getValue());
            system.setDescricao_solucao_4(txtDescricaoSolucao4.getText());
            system.setData_solucao_4(DataHora.getTimestampDate(txtDataSolucao4.getDate()));
            Usuario user4 = new Usuario();
            user4.setUser(txtUserSolucao4.getText());
            system.setUser_solucao_4(user4);
            system.setSolucao_5(cmbSolucao5.getSelectedItem().toString());
            system.setNumero_solucao_5((int) txtNumeroSolucao5.getValue());
            system.setDescricao_solucao_5(txtDescricaoSolucao5.getText());
            system.setData_solucao_5(DataHora.getTimestampDate(txtDataSolucao5.getDate()));
            Usuario user5 = new Usuario();
            user5.setUser(txtUserSolucao5.getText());
            system.setUser_solucao_5(user5);
            system.setSolucao_6(cmbSolucao6.getSelectedItem().toString());
            system.setNumero_solucao_6((int) txtNumeroSolucao6.getValue());
            system.setDescricao_solucao_6(txtDescricaoSolucao6.getText());
            system.setData_solucao_6(DataHora.getTimestampDate(txtDataSolucao6.getDate()));
            Usuario user6 = new Usuario();
            user6.setUser(txtUserSolucao6.getText());
            system.setUser_solucao_6(user6);
            system.setSolucao_7(cmbSolucao7.getSelectedItem().toString());
            system.setNumero_solucao_7((int) txtNumeroSolucao7.getValue());
            system.setDescricao_solucao_7(txtDescricaoSolucao7.getText());
            system.setData_solucao_7(DataHora.getTimestampDate(txtDataSolucao7.getDate()));
            Usuario user7 = new Usuario();
            user7.setUser(txtUserSolucao7.getText());
            system.setUser_solucao_7(user7);
            system.setSolucao_8(cmbSolucao8.getSelectedItem().toString());
            system.setNumero_solucao_8((int) txtNumeroSolucao8.getValue());
            system.setDescricao_solucao_8(txtDescricaoSolucao8.getText());
            system.setData_solucao_8(DataHora.getTimestampDate(txtDataSolucao8.getDate()));
            Usuario user8 = new Usuario();
            user8.setUser(txtUserSolucao8.getText());
            system.setUser_solucao_8(user8);
            system.setSolucao_9(cmbSolucao9.getSelectedItem().toString());
            system.setNumero_solucao_9((int) txtNumeroSolucao9.getValue());
            system.setDescricao_solucao_9(txtDescricaoSolucao9.getText());
            system.setData_solucao_9(DataHora.getTimestampDate(txtDataSolucao9.getDate()));
            Usuario user9 = new Usuario();
            user9.setUser(txtUserSolucao9.getText());
            system.setUser_solucao_9(user9);
            system.setData_registro(DataHora.getTimestampDate(new Date()));
            Usuario user_registro = new Usuario();
            user_registro.setUser(System.getProperty("user"));
            system.setUser_name(user_registro);
            systemDAO.createSystemSuitability(system);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao gravar dados: " + e);
        }
    }

}
